@baseUrl = http://localhost:8000

###

GET {{baseUrl}}/tasks/87bc6401-9142-43cf-b208-f28449c44a57
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/tasks
Authorization: Bearer {{token}}

###

POST {{baseUrl}}/tasks
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "bbb",
  "description": "bbb"
}

###

DELETE {{baseUrl}}/tasks/d183a9ed-92cc-4273-ba70-4e08989cd697

###

PATCH {{baseUrl}}/tasks/82db25fb-d5dc-4200-96a1-5082918480bf/status
Content-Type: application/json

{
  "status": "DONE"
}

###

POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "username": "benn",
  "password": "benn123AA"
}

###

# @name login
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "username": "yenn",
  "password": "benn123AA"
}

###

@token = {{login.response.body.accessToken}}